baseURL = "https://vvasuki.github.io/tipiTaka/"
languageCode = "en-us"
title = "त्रिपिटके विश्वासटिप्पणयो"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/tipiTaka/edit/master/content/"
  contactLink = "https://github.com/vvasuki/tipiTaka/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"

[markup.goldmark.renderer]
  unsafe= true