baseURL = "https://vvasuki.github.io/tipiTaka/"
languageCode = "en-us"
title = "त्रिपिटके विश्वासटिप्पणयो"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/tipiTaka/edit/content/"
  contactLink = "https://github.com/vvasuki/tipiTaka/issues/new"
  fullSearchURL = "/full_search"
  env = "production"
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true